---
## The generic directory /var/containers/{{ project_name }}
## for LXD container persistent storage has already been
## set up by generic host-setup playbooks
## Further project-specific container directories should be
## added here
## -----------------------------------------------------------

## Directories for project-specific LXD container persistent storage
## -----------------------------------------------------------------

## Create directory for project ABC container

# Example
# - name: Create a directory for <ABC> container mounts
#   file:
#     path: "/var/containers/{{ project_name }}/<ABC>"
#     state: directory
#     mode: '0755'
